spring:
  application:
    name: nemo-project

datasource:
    # Собираем URL из переменных
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate # Только Liquibase/Flyway меняют схему!
    show-sql: true

# Настройки gRPC сервера
grpc:
  server:
    port: ${GRPC_PORT:9090}
